- name: Configure Nginx Services
  hosts: localhost
  vars:
    backend_dir: "{{ ansible_env.HOME }}/web_printer/printer-management"
    frontend_dir: "{{ ansible_env.HOME }}/web_printer/printer-management-frontend"
    release_path: "/var/www/web_printer/current"

  tasks:
    - name: Configure Nginx
      copy:
        dest: /etc/nginx/sites-available/printerapp
        content: |
          upstream spring_app {
                      server unix:{{ backend_dir }}/printerapp.sock;
                  }
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              server_name printerapp.local;
              location / {
                  alias {{ release_path }}/;
                  index index.html index.htm;
                  try_files $uri $uri/ /index.html;
              }

              location /api {
                  proxy_pass http://spring_app;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Restart Nginx
      become: yes

    - name: Set Nginx permissions
      command: chown -R www-data:www-data {{ release_path }}
      become: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx
      become: yes

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/printerapp
        dest: /etc/nginx/sites-enabled/printerapp
        state: link
      notify: Restart Nginx
      become: yes

      
    - name: Create systemd service for Spring Boot application
      copy:
        dest: /etc/systemd/system/printerapp.service
        content: |
          [Unit]
          Description=Printer sharing Spring Boot application
          After=network.target
          [Service]
          User={{ ansible_user_id }}
          WorkingDirectory={{ backend_dir }}
          ExecStart=/usr/bin/mvn spring-boot:run
          SuccessExitStatus=143
          TimeoutStopSec=10
          Restart=always
          RestartSec=5
          Environment=SPRING_PROFILES_ACTIVE=prod
          Environment=SERVER_PORT=0
          
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          # Ensure socket file is cleaned up on service stop
          ExecStartPre=/bin/rm -f {{ backend_dir }}/printerapp.sock
          ExecStopPost=/bin/rm -f {{ backend_dir}}/printerapp.sock
          
          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd daemon
      notify: Start Spring Boot Service
      become: yes
    
    
    - name: Enable and start Spring Boot service
      systemd:
        name: printerapp
        enabled: yes
        state: started
      become: yes

  handlers:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      become: yes
      
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
        
    - name: Start Spring Boot Service
      systemd:
        name: printerapp
        state: started
