tasks:
# - name: Install loki and promtail packages
  #   apt:
  #     name:
  #       - loki
  #       # - promtail
  #     state: present
  #   when: ansible_os_family == "Debian"

  # - name: Create Loki config
  #   copy:
  #     dest: /etc/loki/loki.yaml
  #     content: |
  #       auth_enabled: false
  #       server:
  #         http_listen_port: 3100
  #       ingester:
  #         lifecycler:
  #           address: 127.0.0.1
  #           ring:
  #             kvstore:
  #               store: inmemory
  #           final_sleep: 0s
  #         chunk_idle_period: 5m
  #         chunk_retain_period: 30s
  #       schema_config:
  #         configs:
  #           - from: 2020-05-15
  #             store: boltdb
  #             object_store: filesystem
  #             schema: v11
  #             index:
  #               prefix: index_
  #               period: 168h
  #       storage_config:
  #         boltdb:
  #           directory: /tmp/loki/index
  #         filesystem:
  #           directory: /tmp/loki/chunks
  #       limits_config:
  #         enforce_metric_name: false
  #         reject_old_samples: true
  #         reject_old_samples_max_age: 168h
  #       chunk_store_config:
  #         max_look_back_period: 0s
  #       table_manager:
  #         retention_deletes_enabled: false
  #         retention_period: 0s
  #   become: yes

  # - name: Create systemd service for Loki
  #   copy:
  #     dest: /etc/systemd/system/loki.service
  #     content: |
  #       [Unit]
  #       Description=Loki service
  #       After=network.target

  #       [Service]
  #       Type=simple
  #       ExecStart=/usr/local/bin/loki -config.file /etc/loki/loki.yaml

  #       [Install]
  #       WantedBy=multi-user.target
  #   become: yes
    
  # - name: Reload systemd daemon
  #   systemd:
  #     daemon_reload: yes
  #   become: yes
    
  # - name: Enable and start Loki service
  #   systemd:
  #     name: loki
  #     enabled: yes
  #     state: started
  #   become: yes

  # - name: Create Promtail config
  #   copy:
  #     dest: /etc/loki/promtail.yaml
  #     content: |
  #       server:
  #         http_listen_port: 9080
  #         grpc_listen_port: 0

  #       positions:
  #         filename: /tmp/positions.yaml

  #       clients:
  #         - url: http://localhost:3100/loki/api/v1/push

  #       scrape_configs:
  #         - job_name: system
  #           static_configs:
  #             - targets:
  #                 - localhost
  #               labels:
  #                 job: varlogs
  #                 __path__: /var/log/*log
  #         - job_name: spring_boot
  #           static_configs:
  #             - targets:
  #                 - localhost
  #               labels:
  #                 job: spring_boot
  #                 __path__: {{ backend_dir }}logs/*.log
  #   become: yes

  # - name: Create systemd service for Promtail
  #   copy:
  #     dest: /etc/systemd/system/promtail.service
  #     content: |
  #       [Unit]
  #       Description=Promtail service
  #       After=network.target

  #       [Service]
  #       Type=simple
  #       ExecStart=/usr/local/bin/promtail -config.file /etc/promtail/promtail.yaml

  #       [Install]
  #       WantedBy=multi-user.target
  #   become: yes
    
  # - name: Reload systemd daemon
  #   systemd:
  #     daemon_reload: yes
  #   become: yes
    
  # - name: Enable and start Promtail service
  #   systemd:
  #     name: promtail
  #     enabled: yes
  #     state: started
  #   become: yes
