---
- name: Prometheus Configuration
  hosts: localhost
  become: yes
  vars:
    prometheus_version: "2.54.1"
    prometheus_install_dir: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"
    prometheus_config_dir: "/etc/prometheus"
  tasks:
    - name: Check if Prometheus is already installed
      stat:
        path: "{{ prometheus_install_dir }}/prometheus"
      register: prometheus_check

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ prometheus_config_dir }}"
        - "/var/lib/prometheus"

    - name: Install and configure Prometheus
      block:
        - name: Download Prometheus
          get_url:
            url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
            dest: /tmp/prometheus.tar.gz
          register: prometheus_download
          when: not prometheus_check.stat.exists

        - name: Extract Prometheus
          unarchive:
            src: /tmp/prometheus.tar.gz
            dest: /opt/
            remote_src: yes
          when: not prometheus_check.stat.exists

        - name: Configure Prometheus
          copy:
            dest: "{{ prometheus_config_dir }}/prometheus.yml"
            content: |
              global:
                scrape_interval: 15s
              scrape_configs:
                - job_name: 'spring_boot_app'
                  metrics_path: '/actuator/prometheus'
                  static_configs:
                    - targets: ['localhost:8080']

        - name: Create systemd service for Prometheus
          copy:
            dest: /etc/systemd/system/prometheus.service
            content: |
              [Unit]
              Description=Prometheus
              Wants=network-online.target
              After=network-online.target
              
              [Service]
              User=prometheus
              ExecStart={{ prometheus_install_dir }}/prometheus --config.file {{ prometheus_config_dir }}/prometheus.yml --storage.tsdb.path /var/lib/prometheus
              
              [Install]
              WantedBy=default.target

        - name: Ensure prometheus user exists
          user:
            name: prometheus
            system: yes
            shell: /sbin/nologin

        - name: Set ownership for Prometheus directories
          file:
            path: "{{ item }}"
            owner: prometheus
            group: prometheus
            recurse: yes
          loop:
            - "{{ prometheus_install_dir }}"
            - "{{ prometheus_config_dir }}"
            - "/var/lib/prometheus"

        - name: Reload systemd daemon
          systemd:
            daemon_reload: yes

        - name: Enable and start Prometheus service
          systemd:
            name: prometheus
            enabled: yes
            state: started

      when: not prometheus_check.stat.exists

    - name: Display message if Prometheus is already installed
      debug:
        msg: "Prometheus {{ prometheus_version }} is already installed. Skipping installation."
      when: prometheus_check.stat.exists
