- name: Install Prometheus and configure services
  hosts: localhost
  vars:
    prometheus_version: "2.54.1"
  block:
    - name: Install Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
      become_user: "{{ ansible_user_id }}"
      become: yes
      register: prometheus_download

    - name: Set flag for successful download
      set_fact:
        prometheus_download_success: true
      when: prometheus_download is success

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes
      become: yes
      when: prometheus_download_success | default(false)

    - name: Configure Prometheus
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'spring_boot_app'
              metrics_path: '/actuator/prometheus'
              static_configs:
                - targets: ['localhost:8080']
      become: yes
      when: prometheus_download_success | default(false)

    - name: Create systemd service for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target
          [Service]
          User=prometheus
          ExecStart=/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus --config.file /etc/prometheus/prometheus.yml
          [Install]
          WantedBy=default.target
      become: yes
      when: prometheus_download_success | default(false)

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      become: yes
      
    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
      become: yes
      when: prometheus_download_success | default(false)

  rescue:
    - name: Set flag for failed download
      set_fact:
        prometheus_download_success: false

    - name: Display error message
      debug:
        msg: "Prometheus download failed. Skipping Prometheus installation and configuration."
